# **텐서(tensor)**
배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조입니다. 파이토치(PyTorch)에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)합니다.

다차원의 데이터 표현을 위해 사용.

In [2]:
import torch
import numpy as np   #Numpy 배열을 사용하기 위해 import

# **텐서 초기화** 


---


**0) 초기화 되지 않은 텐서**

In [4]:
x1 = torch.empty(3, 3)
print(x1)
x2 = torch.ones(3, 3)
print(x2)

tensor([[ 9.3911e-36,  0.0000e+00,  1.4013e-45],
        [ 6.9141e-06,  2.0000e+00,  4.5417e+03],
        [ 0.0000e+00,  1.1052e+04, -1.0842e-19]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


**1) 데이터로부터 직접(directly) 생성하기**

데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형(data type)은 **자동으로 유추합니다.**

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [ ]:
print(f"Ones Tensor: \n {x_data} \n")

Ones Tensor: 
 tensor([[1, 2],
        [3, 4]]) 



**2) NumPy 배열로부터 생성하기**

텐서는 NumPy 배열로 생성할 수 있습니다. (그 반대도 가능합니다 - NumPy 변환(Bridge) - 참고)

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**3) 다른 텐서로부터 생성하기 (_like)**

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.

In [ ]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6557, 0.6839],
        [0.8779, 0.2470]]) 



**4) 무작위(random) 또는 상수(constant) 값을 사용하기**

shape 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [ ]:
shape = (2,3,)   # 모양
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")   # 'shape' 모양의 텐서에 무작위 값 입력
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6932, 0.6086, 0.4927],
        [0.0849, 0.1543, 0.3961]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


**참고)**

**torch.rand(a, b) :** 0 ~ 1사이의 값을 갖는 a x b 텐서생성 

**torch.zeros(a, b) :**  0 값을 가진 a x b의 tensor 생성

**torch.ones(a, b) :**  1 값을 가진 a x b의 tensor 생성

**torch.zeros_like(input) :**  input의 크기와 같고 모든 값이 0인 tensor 생성

**torch.ones_like(input) :**  input의 크기와 같고 모든 값이 1인 tensor 생성

**torch.eye(a) :** 사선 방향이 1인 a x a 텐서 생성


---

https://seungjuitmemo.tistory.com/102


# **텐서의 속성(Attribute)**

---



텐서의 속성은 텐서의 모양(shape), 자료형(dtype) 및 어느 장치(device)에 저장되는지를 나타냅니다.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")   #모양
print(f"Datatype of tensor: {tensor.dtype}")   #자료형
print(f"Device tensor is stored on: {tensor.device}")   #장치

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


ex) 2 x 4 크기, double 타입, 1로 채워진 텐서 정의

In [ ]:
y = torch.ones(2, 4, dtype=torch.double)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


# **텐서 연산(Operation)**

---



전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등.

각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행.

***- Colab을 사용한다면, Edit > Notebook Settings 에서 GPU를 할당할 수 있습니다.***

기본적으로 텐서는 CPU에 생성 .to 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있음. 

***- 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요!***

In [ ]:
# GPU가 존재하면 텐서를 이동합니다

if torch.cuda.is_available():
    tensor = tensor.to("cuda")



---



**NumPy식의 표준 인덱싱과 슬라이싱**

[배열](https://datascienceschool.net/01%20python/03.01%20%EB%84%98%ED%8C%8C%EC%9D%B4%20%EB%B0%B0%EC%97%B4.html)

[인덱싱과 슬라이싱](https://bodhi-sattva.tistory.com/65)

In [13]:
tns = torch.arange(1, 17).reshape(4, 4)
print(f"First row: {tns[0]}")          # 첫째축 0번째만 지정
print(f"First column: {tns[:, 0]}")    # 첫째축 전부. 둘째축 0번째 지정
print(f"Last column: {tns[..., -1]}")  # == [:::, -1], 첫째축 전부, 뒤에서 -1번째 지정
print(tns)


First row: tensor([1, 2, 3, 4])
First column: tensor([ 1,  5,  9, 13])
Last column: tensor([ 4,  8, 12, 16])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


**텐서 합치기** 

torch.cat 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다. torch.cat 과 미묘하게 다른 또 다른 텐서 결합 연산인 torch.stack 도 참고해보세요.

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1) 
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산(Arithmetic operations)**

In [ ]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# 행렬 곱 '@'
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
# 요소별 곱 '*'
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일-요소(single-element) 텐서**

텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환할 수 있습니다

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기(in-place) 연산**

연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, _ 접미사를 갖습니다. 

예를 들어: x.copy_(y) 나 x.t_() 는 x 를 변경합니다.

In [ ]:
print(f"{tensor} \n")   # 원래 값 출력
tensor.add_(5) 
print(tensor)   # 바꿔치기 연산된 'tensor'값 출력

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


*바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서, 사용을 권장하지 않습니다.*

# **NumPy 변환(Bridge)**

---



CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

**텐서를 NumPy 배열로 변환하기**

In [14]:
t = torch.ones(5)
print(f"t: {t}")  # 텐서
n = t.numpy()     # 변환
print(f"n: {n}")  # 넘파이 배열

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


**NumPy 배열을 텐서로 변환하기**

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

텐서에 변경 사항이 생기면 NumPy 배열에도 반영 (반대의 경우도 마찬가지)



In [ ]:
t.add_(1)   # 텐서에 값에 1 더하기
print(f"t: {t}")
print(f"n: {n}")   # 넘파이 배열엔 연산하지 않았지만 같이 변경 됨

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [ ]:
np.add(n, 1, out=n)   # 넘파이 배열 값에 1 더하기, 위에서 값이 2가 됐으면, 2 + 1 = 3
print(f"t: {t}")
print(f"n: {n}")

t: tensor([4., 4., 4., 4., 4.])
n: [4. 4. 4. 4. 4.]
